### ISSUE TITLE
Implement the webapp-test project as part of the pipeline

### ISSUE THREAD

**Issue by ANicholasson** [AutoPacker-OSS/AutoPacker#186]

**Comment by ANicholasson** [comment]
Run the selenium tests after booting up system using docker-compose. 

For reference:
```yml
selenium:
      image: selenium/standalone-chrome
      ports:
      - 4444:4444
      restart: always
I Python crawler coden:
chrome_options = Options()
    chrome_options.add_argument('--disable-dev-shm-usage')
    chrome_options.add_argument("--headless")
    driver = webdriver.Remote('http://selenium:4444/wd/hub', desired_capabilities=DesiredCapabilities.CHROME,
                              options=chrome_options)
```
